baseURL = 'https://fawwaz.anvilen.space/'
languageCode = 'en-us'
title = "Fawwaz Anvilen"
theme = "faw-minimal"

[build]
writeStats = true

[markup]
  defaultMarkdownHandler = 'goldmark'
  [markup.goldmark.renderer]
    unsafe = true

[menu]
  [[menu.main]]
    name = "Projects"
    url = "/projects/"
    weight = 10
  [[menu.main]]
    name = "Books"
    url = "/books/"
    weight = 20
  [[menu.main]]
    name = "Notes"
    url = "https://notes.fawwaz.anvilen.space"
    weight = 30