baseURL = 'https://fawwaz.anvilen.space/'
languageCode = 'en-us'
title = "Faw's Web Site"
theme = "faw-monospace"

[build]
writeStats = true

[markup]
  defaultMarkdownHandler = 'goldmark'
  [markup.goldmark.renderer]
    unsafe = true

# [module]
#   [[module.mounts]]
#     source = "assets"
#     target = "assets"
#   [[module.mounts]]
#     source = "hugo_stats.json"
#     target = "assets/hugo_stats.json"
#   [[module.mounts]]
#     source = 'content'
#     target = 'content'
    # excludeFiles = ['themes/**/content/**/*.md']

[menu]
  [[menu.main]]
    name = "Home"
    url = "/"
    weight = 10
  [[menu.main]]
    name = "About"
    url = "/about/"
    weight = 20
  [[menu.main]]
    name = "Blog"
    url = "/blog/"
    weight = 30
  [[menu.main]]
    name = "Projects"
    url = "/projects/"
    weight = 40
  [[menu.main]]
    name = "Bets"
    url = "/bets/"
    weight = 50
  [[menu.main]]
    name = "Books"
    url = "/books/"
    weight = 60
  [[menu.main]]
    name = "Notes"
    url = "https://notes.fawwaz.anvilen.space"
    weight = 70